apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: prxwiwnsm-python
  janus-idp.io/tekton: prxwiwnsm-python
  backstage.io/kubernetes-id: prxwiwnsm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: prxwiwnsm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
